### ISSUE TITLE
About point cloud generation task's parameters

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#10]
For  point cloud generation task of this paper, I want to confirm the parameters. 
![`@0R4@GOELVRGAFEW5(Q3BD](https://user-images.githubusercontent.com/32491440/91784404-70510080-ec35-11ea-9097-8ecdc9fb37d6.png)
Are the networks trained under those parameters which are different from the code?

**Comment by EchoTHChen** [comment]
And I wonder what the chamfer distance results of the networks are?

**Comment by siyuan2018** [comment]
We used a FoldingNet-like network, which is slightly different from the original FoldingNet paper, and similar to the architecture in paper _[Real-time Soft Body 3D Proprioception via Deep Vision-based Sensing](https://arxiv.org/abs/1904.03820)_. 

For the chamfer distance, the training loss is around 0.04 in the last iterations after converging.

**Comment by EchoTHChen** [comment]
Thanks! I find the point clouds are just be divided by _max_range_. If i want to use mean value or mid value to normalize point clouds,  how point clouds should be normalized to [0,1] or [-0.5, 0.5] for all axes in _data_collect.py_ file?

**Comment by siyuan2018** [comment]
Hi, I think one way you can try is, after you normalize with mean or mid value, check the range of all coordinates, then do the normalization again.
