### ISSUE TITLE
The code of AtlasNet in this paper like Code/Point_cloud_generation/resfoldnet.py?

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#11]
I want to compare my new networks with AtlasNet-like architecture in this paper. So can I have access to the code of AtlasNet like _Code/Point_cloud_generation/resfoldnet.py_ which are finished by you? Thanks!

**Comment by siyuan2018** [comment]
Please check the original AtlasNet paper. We just modified the first layer, which takes three images as input. Other architectures and parameters are all the same with the original AtlasNet paper. We have explained how we did it in our paper.
