### ISSUE TITLE
Model for point cloud generation

### ISSUE THREAD

**Issue by guist** [ai4ce/SPARE3D#16]
Hello,

I am interested in the model for point cloud generation but the link to the baseline models does not seem to work:

https://github.com/ai4ce/spare3d/Code

Is it still available?

Thanks,
Guillaume

**Comment by simbaforrest** [comment]
Thanks for your interest! Not sure if @WenyuHan-LiNa still has that. But it's an old model that cannot solve the problem anyway. What do you want to do with the model? @guist

**Comment by guist** [comment]
Hello,

Thank you very much for the answer. I was interested in reconstructing a 3D model from 2D drawings, but in the meantime, I found another solution.

Best,
Guillaume
