### ISSUE TITLE
Want to get access to the ABC datasets' STEP files.

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#3]
Hello! I would like to get the left and bottom views of  ABC datasets. I would appreciate it very much if  you could give me the download link of  the ABC datasets' STEP files..

**Comment by WenyuHan-LiNa** [comment]
hello, you could find the whole ABC dataset here: 
https://deep-geometry.github.io/abc-dataset/

**Comment by EchoTHChen** [comment]
thanks



---Original---
