### ISSUE TITLE
how to get the came parameters for mapping point clouds to image plane?

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#6]
I want to map point clouds to the three-view image. But I don't know the came intrinsic parameters and extrinsic parameters. How can I get the those parameters?

**Comment by simbaforrest** [comment]
Please see [here](https://github.com/ai4ce/SPARE3D/blob/master/Data_generation_script/model2svg.py#L35-L97). There is no need for any camera intrinsic parameters because we are using parallel projection.

**Comment by simbaforrest** [comment]
@EchoTHChen If the above answered your question, please consider closing this issue. Thanks.

**Comment by EchoTHChen** [comment]
thanks！



---Original---
