### ISSUE TITLE
there are some problems about the three-views input images.

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#7]
I found 8622_right.png, 1563_right.png and 1553_front.png are blank in Task_data/ABC_data/pointcloud_generation directory which made my network's training loss become nan. So could you give me right images for those three images if possible? Or Can I just remove those from my datasets?

**Comment by simbaforrest** [comment]
We might have some small portion of problematic images (tiny or symmetric images, etc.). We are working on detecting and removing them from the dataset. You should be able to receive an announcement on GitHub and the SPARE3D project webpage by the end of July. For now, you can simply remove it from the dataset yourself.

@WenyuHan-LiNa @Yf-Xue

**Comment by EchoTHChen** [comment]
thanks！



---Original---

**Comment by simbaforrest** [comment]
@EchoTHChen The problems have been fixed. You can find the updates [here](https://github.com/ai4ce/SPARE3D/#changes-after-cvpr20) and in our updated [arXiv paper](https://arxiv.org/abs/2003.14034).
