### ISSUE TITLE
is the original parameters for the point cloud generation networks(resfoldnet) available?

### ISSUE THREAD

**Issue by EchoTHChen** [ai4ce/SPARE3D#8]
Hello! I found this code's results were not as good as the visualization results of the paper. So I wonder if I can get the original code and parameters for the paper's result.

**Comment by siyuan2018** [comment]
Hi, in the paper, we selected the object model, whose index are: 00009129, 00009233, 00009299, 00009300 in the original ABC data set. Can you try these four models? If you still cannot obtain the same results as we provided in the paper, can you send me your email, so I can share the trained model file with you? Thx.

**Comment by simbaforrest** [comment]
I am closing this issue as it seems to be resolved.
